CREATE TABLE T_USUARIO (
    ID_USER VARCHAR2(36) NOT NULL,

    NM_USER VARCHAR2(255) NOT NULL,
    DS_EMAIL VARCHAR2(255) NOT NULL,
    DS_SENHA VARCHAR2(255) NOT NULL,
    DT_CADASTRO DATE DEFAULT SYSDATE,

    CONSTRAINT PK_USER PRIMARY KEY (ID_USER),
    CONSTRAINT UK_USER_EMAIL UNIQUE (DS_EMAIL)
);