CREATE TABLE T_FUNCIONARIO (
    ID_FUNCIONARIO VARCHAR2(36) PRIMARY KEY,
    NM_FUNCIONARIO VARCHAR2(100) NOT NULL,
    DS_GENERO VARCHAR2(20) NOT NULL,
    FL_PCD NUMBER(1) DEFAULT 0 NOT NULL,
    DS_CARGO VARCHAR2(100) NOT NULL,
    DS_ETNIA VARCHAR2(50),
    NU_IDADE NUMBER(3),
    DS_DEPARTAMENTO VARCHAR2(100),
    DT_CONTRATACAO DATE DEFAULT SYSDATE
);