CREATE TABLE T_FEEDBACK (
    ID_FEEDBACK VARCHAR2(36) PRIMARY KEY,
    DS_SENTIMENTO VARCHAR2(20) NOT NULL,
    DS_COMENTARIO VARCHAR2(500),
    DT_FEEDBACK DATE NOT NULL,
    ID_FUNCIONARIO VARCHAR2(36) NOT NULL,
    CONSTRAINT FK_FEEDBACK_FUNC FOREIGN KEY (ID_FUNCIONARIO)
        REFERENCES T_FUNCIONARIO (ID_FUNCIONARIO)
);