CREATE TABLE TB_CANDIDATO (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    GENERO VARCHAR2(30),
    ETNIA VARCHAR2(50),
    LOCALIZACAO VARCHAR2(100),
    EXPERIENCIA_ANOS NUMBER(3),
    DATA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
