CREATE TABLE TB_VAGA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITULO VARCHAR2(100) NOT NULL,
    DESCRICAO VARCHAR2(300),
    DEPARTAMENTO VARCHAR2(100),
    NIVEL VARCHAR2(50),
    META_DIVERSIDADE NUMBER(3) DEFAULT 50,
    DATA_ABERTURA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

