CREATE TABLE TB_SELECAO (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CANDIDATO NUMBER NOT NULL,
    ID_VAGA NUMBER NOT NULL,
    STATUS VARCHAR2(30) DEFAULT 'PENDENTE',
    PRIORIZADO CHAR(1) DEFAULT 'N',
    DATA_AVALIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SEL_CAND FOREIGN KEY (ID_CANDIDATO) REFERENCES TB_CANDIDATO(ID),
    CONSTRAINT FK_SEL_VAGA FOREIGN KEY (ID_VAGA) REFERENCES TB_VAGA(ID)
);
